### ISSUE TITLE
Default keyboard action when adding an identity

### ISSUE THREAD

**Issue by RobTrainer** [digitalbazaar/authorization.io#31]
When adding an identity, pressing the Enter key (mobile or PC) does not submit (Add) the form. The Add button must be explicitly clicked.

**Comment by mattcollier** [comment]
I think the current behavior is OK because it's good to make sure that the user has considered the 'Remember me on this device' option before clicking 'Add'.

@RobTrainer Is the 'Add' button not visible on a mobile device or is it otherwise unclear that the button would need to be pressed to proceed?

**Comment by RobTrainer** [comment]
But it is not the way 99% of the applications work. <ENTER> for the submit action and <ESC> for the cancel action.

**Comment by dlongley** [comment]
If the button isn't disabled, then I think it's ok to make it so you can press enter to submit. I think in this case, because the default is that the "Remember me" is unchecked it's ok.

I will say that I find it very annoying when the default is to have an option like that checked and then my phone keyboard obscures it from view -- so I don't even see it when I press enter and it submits a value I don't even know about or know how to easily change. It's true that there are a number of applications that do that, I it's very frustrating to some users. But, again, because the default is not to automatically store important, long-term access credentials on the phone, I think it's ok in this case.

**Comment by dlongley** [comment]
Fixed by c64f3f9085f7e67aa9113329a0363bf2ed189f99.
